version: "2"
services:

  uwsgi:
    build: ./uwsgi
    volumes:
      - ./uwsgi:/var/www/
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nuxt:
    build: ./nuxt
    volumes:
      - ./nuxt:/src/
      - /src/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - uwsgi
      - nuxt
    ports:
      - "5000:80"
    environment:
      TZ: "Asia/Tokyo"

  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期化時に実行するSQL
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_pass
    ports:
      - "3306:3306"
